# -*- coding: utf-8 -*-
"""assignment1cv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b115S6tFrJEHcATif3utBkLgAenfDW52

**COMPUTER VISION**

**ASSIGNMENT NO : 1**

**Name:** Siddhi Naik  
**Roll No:** 235  
**Seat No:** B224014  
**PRN:** 0120190091
"""
"""<u>USING MEDIAN BLUR AND SALT AND PEPPER NOISY IMAGE</u>
"""

#Uploading image and reading it.
#from google.colab import files  
import cv2  
import streamlit as st
#uploaded = files.upload()  
image = cv2.imread('C:/Users/lenovo/Desktop/ass1/noise.png', -1)

#Displaying image  
#from google.colab.patches import cv2_imshow
st.text("input image for median blur") 
st.image([image])

import matplotlib.pyplot as plt
filtersize = [3, 5, 11, 15]
filtersizeTitle = ['3 X 3', '5 X 5', '11 X 11', '15 X 15'] 
for i in range (4):
  print(filtersizeTitle[i])
  imageSol = cv2.medianBlur(image, ksize = filtersize[i])
  st.text("median blur output") 
  st.image([imageSol])

"""<u>USING GAUSSIAN BLUR</u>  """

#Uploading image and reading it.

#from google.colab import files
import cv2
#uploaded = files.upload()
image = cv2.imread('C:/Users/lenovo/Desktop/ass1/scenery.jfif', -1)
st.text("input image for gaussian blur") 
st.image([image])

for i in range (4):
  filtersize = [3, 5, 11, 15]
  filtersizeTitle = ['3 X 3', '5 X 5', '11 X 11', '15 X 15']
  print(filtersizeTitle[i])
  gaussian = cv2.GaussianBlur(image, ksize = (filtersize[i], filtersize[i]), sigmaX = 0, sigmaY = 0)
  st.text("gaussian blur output")
  st.image([gaussian])